// val a = Eq.derived[ISB]
// val b = Eq.derived[OptionInt]
// val b1 = Eq.derived[IList]

// implicitly[K1.StagedProductInstances[Functor0, Box]]
// implicitly[K1.StagedInstances[Functor0, Box]]
// K1.StagedProductInstances[Functor0, Box]
// val f0 = Functor0.derived[Box]
// val d = Functor.derived[Box]
// val s = Functor.derived[Sm]
// val o = Functor.derived[Opt]
// val c = Functor.derived[CList]

// val v1 = Eq.derived[P100]
// val v2 = Eq.derived[C100]
// val v3 = Functor.derived[PK100]
// val v4 = Functor.derived[CK100]
// val v5 = Inlined.Eq.derived[P100]
// val v6 = Inlined.Eq.derived[C100]

// val inlinedEqDerivedC10  = Inlined.Eq.derived[C10]
// val inlinedEqDerivedC20  = Inlined.Eq.derived[C20]
// val inlinedEqDerivedC30  = Inlined.Eq.derived[C30]
// val inlinedEqDerivedC40  = Inlined.Eq.derived[C40]
// val inlinedEqDerivedC50  = Inlined.Eq.derived[C50]
// val inlinedEqDerivedC60  = Inlined.Eq.derived[C60]
// val inlinedEqDerivedC70  = Inlined.Eq.derived[C70]
// val inlinedEqDerivedC80  = Inlined.Eq.derived[C80]
// val inlinedEqDerivedC90  = Inlined.Eq.derived[C90]
// val inlinedEqDerivedC100 = Inlined.Eq.derived[C100]

// val inlinedEqDerivedP0   = Inlined.Eq.derived[P0]
// val inlinedEqDerivedP10  = Inlined.Eq.derived[P10]
// val inlinedEqDerivedP20  = Inlined.Eq.derived[P20]
// val inlinedEqDerivedP30  = Inlined.Eq.derived[P30]
// val inlinedEqDerivedP40  = Inlined.Eq.derived[P40]
// val inlinedEqDerivedP50  = Inlined.Eq.derived[P50]
// val inlinedEqDerivedP60  = Inlined.Eq.derived[P60]
// val inlinedEqDerivedP70  = Inlined.Eq.derived[P70]
// val inlinedEqDerivedP80  = Inlined.Eq.derived[P80]
// val inlinedEqDerivedP90  = Inlined.Eq.derived[P90]
// val inlinedEqDerivedP100 = Inlined.Eq.derived[P100]

val stagedEqDerivedC10   = Eq.derived[C10]
// val stagedEqDerivedC20   = Eq.derived[C20]
// val stagedEqDerivedC30   = Eq.derived[C30]
// val stagedEqDerivedC40   = Eq.derived[C40]
// val stagedEqDerivedC50   = Eq.derived[C50]
// val stagedEqDerivedC60   = Eq.derived[C60]
// val stagedEqDerivedC70   = Eq.derived[C70]
// val stagedEqDerivedC80   = Eq.derived[C80]
// val stagedEqDerivedC90   = Eq.derived[C90]
// val stagedEqDerivedC100  = Eq.derived[C100]

// val stagedEqDerivedP0    = Eq.derived[P0]
// val stagedEqDerivedP10   = Eq.derived[P10]
// val stagedEqDerivedP20   = Eq.derived[P20]
// val stagedEqDerivedP30   = Eq.derived[P30]
// val stagedEqDerivedP40   = Eq.derived[P40]
// val stagedEqDerivedP50   = Eq.derived[P50]
// val stagedEqDerivedP60   = Eq.derived[P60]
// val stagedEqDerivedP70   = Eq.derived[P70]
// val stagedEqDerivedP80   = Eq.derived[P80]
// val stagedEqDerivedP90   = Eq.derived[P90]
// val stagedEqDerivedP100  = Eq.derived[P100]

// val shapeless3EqDerivedC10   = Shapeless3.Eq.derived[C10]
// val shapeless3EqDerivedC20   = Shapeless3.Eq.derived[C20]
// val shapeless3EqDerivedC30   = Shapeless3.Eq.derived[C30]
// val shapeless3EqDerivedC40   = Shapeless3.Eq.derived[C40]
// val shapeless3EqDerivedC50   = Shapeless3.Eq.derived[C50]
// val shapeless3EqDerivedC60   = Shapeless3.Eq.derived[C60]
// val shapeless3EqDerivedC70   = Shapeless3.Eq.derived[C70]
// val shapeless3EqDerivedC80   = Shapeless3.Eq.derived[C80]
// val shapeless3EqDerivedC90   = Shapeless3.Eq.derived[C90]
// val shapeless3EqDerivedC100  = Shapeless3.Eq.derived[C100]

// val shapeless3EqDerivedP0    = Shapeless3.Eq.derived[P0]
// val shapeless3EqDerivedP10   = Shapeless3.Eq.derived[P10]
// val shapeless3EqDerivedP20   = Shapeless3.Eq.derived[P20]
// val shapeless3EqDerivedP30   = Shapeless3.Eq.derived[P30]
// val shapeless3EqDerivedP40   = Shapeless3.Eq.derived[P40]
// val shapeless3EqDerivedP50   = Shapeless3.Eq.derived[P50]
// val shapeless3EqDerivedP60   = Shapeless3.Eq.derived[P60]
// val shapeless3EqDerivedP70   = Shapeless3.Eq.derived[P70]
// val shapeless3EqDerivedP80   = Shapeless3.Eq.derived[P80]
// val shapeless3EqDerivedP90   = Shapeless3.Eq.derived[P90]
// val shapeless3EqDerivedP100  = Shapeless3.Eq.derived[P100]

// val stagedFunctorDerivedCK10   = Functor.derived[CK10]
// val stagedFunctorDerivedCK20   = Functor.derived[CK20]
// val stagedFunctorDerivedCK30   = Functor.derived[CK30]
// val stagedFunctorDerivedCK40   = Functor.derived[CK40]
// val stagedFunctorDerivedCK50   = Functor.derived[CK50]
// val stagedFunctorDerivedCK60   = Functor.derived[CK60]
// val stagedFunctorDerivedCK70   = Functor.derived[CK70]
// val stagedFunctorDerivedCK80   = Functor.derived[CK80]
// val stagedFunctorDerivedCK90   = Functor.derived[CK90]
// val stagedFunctorDerivedCK100  = Functor.derived[CK100]

// val stagedFunctorDerivedPK0    = Functor.derived[PK0]
// val stagedFunctorDerivedPK10   = Functor.derived[PK10]
// val stagedFunctorDerivedPK20   = Functor.derived[PK20]
// val stagedFunctorDerivedPK30   = Functor.derived[PK30]
// val stagedFunctorDerivedPK40   = Functor.derived[PK40]
// val stagedFunctorDerivedPK50   = Functor.derived[PK50]
// val stagedFunctorDerivedPK60   = Functor.derived[PK60]
// val stagedFunctorDerivedPK70   = Functor.derived[PK70]
// val stagedFunctorDerivedPK80   = Functor.derived[PK80]
// val stagedFunctorDerivedPK90   = Functor.derived[PK90]
// val stagedFunctorDerivedPK100  = Functor.derived[PK100]

// val shapeless3FunctorDerivedCK10   = Shapeless3.Functor.derived[CK10]
// val shapeless3FunctorDerivedCK20   = Shapeless3.Functor.derived[CK20]
// val shapeless3FunctorDerivedCK30   = Shapeless3.Functor.derived[CK30]
// val shapeless3FunctorDerivedCK40   = Shapeless3.Functor.derived[CK40]
// val shapeless3FunctorDerivedCK50   = Shapeless3.Functor.derived[CK50]
// val shapeless3FunctorDerivedCK60   = Shapeless3.Functor.derived[CK60]
// val shapeless3FunctorDerivedCK70   = Shapeless3.Functor.derived[CK70]
// val shapeless3FunctorDerivedCK80   = Shapeless3.Functor.derived[CK80]
// val shapeless3FunctorDerivedCK90   = Shapeless3.Functor.derived[CK90]
// val shapeless3FunctorDerivedCK100  = Shapeless3.Functor.derived[CK100]

// val shapeless3FunctorDerivedPK0    = Shapeless3.Functor.derived[PK0]
// val shapeless3FunctorDerivedPK10   = Shapeless3.Functor.derived[PK10]
// val shapeless3FunctorDerivedPK20   = Shapeless3.Functor.derived[PK20]
// val shapeless3FunctorDerivedPK30   = Shapeless3.Functor.derived[PK30]
// val shapeless3FunctorDerivedPK40   = Shapeless3.Functor.derived[PK40]
// val shapeless3FunctorDerivedPK50   = Shapeless3.Functor.derived[PK50]
// val shapeless3FunctorDerivedPK60   = Shapeless3.Functor.derived[PK60]
// val shapeless3FunctorDerivedPK70   = Shapeless3.Functor.derived[PK70]
// val shapeless3FunctorDerivedPK80   = Shapeless3.Functor.derived[PK80]
// val shapeless3FunctorDerivedPK90   = Shapeless3.Functor.derived[PK90]
// val shapeless3FunctorDerivedPK100  = Shapeless3.Functor.derived[PK100]
