// val a = Eq.derived[ISB]
// val b = Eq.derived[OptionInt]
// val b1 = Eq.derived[IList]

// implicitly[K1.StagedProductInstances[Functor0, Box]]
// implicitly[K1.StagedInstances[Functor0, Box]]
// K1.StagedProductInstances[Functor0, Box]
// val f0 = Functor0.derived[Box]
// val d = Functor.derived[Box]
// val s = Functor.derived[Sm]
// val o = Functor.derived[Opt]
// val c = Functor.derived[CList]

// val v1 = Staged.Eq.derived[P100]
// val v2 = Staged.Eq.derived[C100]
// val v3 = Staged.Functor.derived[PK100]
// val v4 = Staged.Functor.derived[CK100]
val v5 = Inlined.Eq.derived[P100]
val v6 = Inlined.Eq.derived[C100]
